### PR TITLE
👍 small (non javascript related) improvements

### PR DESCRIPTION
**Pull request by Dot32IsCool**
This pull request adds:

- A [Favicon](https://en.m.wikipedia.org/wiki/Favicon); specifically the [illogicalapple logo](https://avatars.githubusercontent.com/u/80916557?v=4)
- An updating mouse cursor for when hovering over buttons, making it feel more clickable

I was looking into making facts less common the more they've appeared, but due to the structure of the website it is very hard to tell how many times a given fact has shown.

My favourite fact is that the sun is **still a deadly laser** 👀

### CODE REVIEW

**Comment by illogicalapple** [comment]
I didn't add that mouse pointer for a [reason](https://www.w3.org/TR/CSS21/ui.html#propdef-cursor): the W3C User Interface Guidelines says that pointers should represent links.

**Comment by illogicalapple** [comment]
When you want a [random fact](https://illogicalapple.github.io/completely-true-facts/facts/rand), it **always** redirects you to `/facts/rand`, so store the random number in a variable, and make a cookie.

**Comment by Dot32IsCool** [comment]
The reason you can't make it a cookie is because a cookie will not be deleted if you close and reopen your website. Over time every fact will become "rare", which is not necessary.

Secondly, that button you have actually *is* a link. Clicking the button links you to a new page of the website, which is why it felt odd to me that it wasn't properly implemented. 
Guidelines are also just that; guidelines. They aren't rules, because individual websites will need to bend them slightly differently. I believe if not adding the pointer hurts the user experience, then you should consider doing something differently.

**Comment by illogicalapple** [comment]
You could set the cookie to be deleted every day.

**Comment by Dot32IsCool** [comment]
That is true i suppose. I guess im used to desktop development, where downloading information can cause lag. Cookies may be a fine way to do it 👍

**Pull request merged**
